name = "plausible-webhook"  # Replace with your project name
compatibility_date = "2025-01-29"
main = "src/index.js"
account_id = "xxx"  # Replace with your Cloudflare account ID

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "plausible-webhook"
# workers_dev = false
vars = { PLAUSIBLE_ENDPOINT = "https://plausible.io/api/event" }

[env.dev]
vars = { PLAUSIBLE_ENDPOINT = "https://plausible.io/api/event" }